# Zed - Userbot # حقوق زد ثـون ومتعوب عليها .. تخمط اذكر المصدر
# من هنا يتم تحميل الثيمات
# theme loaded from here

X = (
    "𓆰 𝑺𝑶𝑼𝑹𝑪𝑬 𝙕𝞝𝘿𝙏𝙃𝙊𝙉 - 𝑪𝑶𝑴𝑴𝑨𝑵𝑫𝑺 𓆪\n"
    "𓍹ⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧ𓍻\n"
    "**⌔∮ قائـمه اوامر الثيمات :**\n\n"
    "⪼ `.ثيم`\n\n\n"
    "𓍹ⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧⵧ𓍻\n"
    "𓆩 𝙎𝙊𝙐𝙍𝘾𝞝 𝙕𝞝𝘿𝙏𝙃𝙊𝙉 - [𝘿𝙀𝙑](t.me/Zedthon) 𓆪"
)

FANAN = "𓆩 𝑺𝑶𝑼𝑹𝑪𝑬 𝙕𝞝𝘿𝙏𝙃𝙊𝙉 - 𝙏𝙃𝙀𝙈𝙀 ثيمـات 𓆪"
sts_fanan = "https://t.me/SSSSllv/36"
sts_fanan2 = "https://t.me/SSSSllv/18" 
sts_fanan3 = "https://t.me/SSSSllv/28"
sts_fanan4 = "https://t.me/SSSSllv/16"
sts_fanan5 = "https://t.me/SSSSllv/32"
sts_fanan6 = "https://t.me/SSSSllv/42"
sts_fanan7 = "https://t.me/SSSSllv/52"
sts_fanan8 = "https://t.me/SSSSllv/48" 
sts_fanan9 = "https://t.me/SSSSllv/72"
sts_fanan10 = "https://t.me/SSSSllv/74"
sts_fanan11 = "https://t.me/SSSSllv/24"
sts_fanan12 = "https://t.me/SSSSllv/30"
sts_fanan13 = "https://t.me/SSSSllv/34"
sts_fanan14 = "https://t.me/SSSSllv/38"
sts_fanan15 = "https://t.me/SSSSllv/40"
sts_fanan16 = "https://t.me/SSSSllv/44"
sts_fanan17 = "https://t.me/SSSSllv/46"
sts_fanan18 = "https://t.me/SSSSllv/50"
sts_fanan19 = "https://t.me/SSSSllv/54"
sts_fanan20 = "https://t.me/SSSSllv/56"
sts_fanan21 = "https://t.me/SSSSllv/58"
sts_fanan22 = "https://t.me/SSSSllv/60"
sts_fanan23 = "https://t.me/SSSSllv/62"
sts_fanan24 = "https://t.me/SSSSllv/64"
sts_fanan25 = "https://t.me/SSSSllv/66"
sts_fanan26 = "https://t.me/SSSSllv/68"
THMAT = "𓆩 𝑺𝑶𝑼𝑹𝑪𝑬 𝙕𝞝𝘿𝙏𝙃𝙊𝙉 - 𝙏𝙃𝙀𝙈𝙀 ثيمـات 𓆪"
sts_attheme = "https://t.me/SSSSllv/35"
sts_attheme2 = "https://t.me/SSSSllv/17" 
sts_attheme3 = "https://t.me/SSSSllv/27"
sts_attheme4 = "https://t.me/SSSSllv/15"
sts_attheme5 = "https://t.me/SSSSllv/31"
sts_attheme6 = "https://t.me/SSSSllv/41"
sts_attheme7 = "https://t.me/SSSSllv/51"
sts_attheme8 = "https://t.me/SSSSllv/47" 
sts_attheme9 = "https://t.me/SSSSllv/71"
sts_attheme10 = "https://t.me/SSSSllv/73"
sts_attheme11 = "https://t.me/SSSSllv/23"
sts_attheme12 = "https://t.me/SSSSllv/29"
sts_attheme13 = "https://t.me/SSSSllv/33"
sts_attheme14 = "https://t.me/SSSSllv/37"
sts_attheme15 = "https://t.me/SSSSllv/39"
sts_attheme16 = "https://t.me/SSSSllv/43"
sts_attheme17 = "https://t.me/SSSSllv/45"
sts_attheme18 = "https://t.me/SSSSllv/49"
sts_attheme19 = "https://t.me/SSSSllv/53"
sts_attheme20 = "https://t.me/SSSSllv/55"
sts_attheme21 = "https://t.me/SSSSllv/57"
sts_attheme22 = "https://t.me/SSSSllv/59"
sts_attheme23 = "https://t.me/SSSSllv/61"
sts_attheme24 = "https://t.me/SSSSllv/63"
sts_attheme25 = "https://t.me/SSSSllv/65"
sts_attheme26 = "https://t.me/SSSSllv/67"

